# Visual image to send to SPANet
sensor_msgs/Image image
# Raw haptic data, assuming 6D, row-wise
float64[] haptic
# Action taken
int8 a_t
float64 loss
# Probability distribution of choosing each action
float64[] p_t
---
# True on success and false on failure.
bool success